name: Build Release Apk

on:
  push:
    tags:
      - v*
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    name: Build app
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@v3

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: adopt

      - name: Get tag name
        run: |
          set -x
          echo "VERSION_TAG=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV    

      - name: Build app
        uses: gradle/gradle-command-action@v2
        with:
          arguments: assembleRelease

      - name: Sign APK
        id: sign_app
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEYSTORE_PASSWORD  }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}

      - name: Clean up build artifacts
        run: |
            set -e
            mv app/build/outputs/apk/release/app-release-unsigned-signed.apk cricskore-${{ env.VERSION_TAG }}.apk

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          name: CricSkore ${{ env.VERSION_TAG }}
          body: App Release
          files: cricskore-${{ env.VERSION_TAG }}.apk
          draft: true
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}