name: Build Release Apk

on: workflow_dispatch

permissions:
  contents: write


jobs:
  build:
    name: Build app
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@v3

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: adopt

      - name: Build app
        uses: gradle/gradle-command-action@v2
        with:
          arguments: assembleRelease

      - name: Sign APK
        id: sign_app
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.SIGNINGKEYBASE64 }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEYSTOREPASSWORD  }}
          keyPassword: ${{ secrets.KEYPASSWORD }}

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          name: CricSkore
          body: App Release
          files: ${{steps.sign_app.outputs.signedReleaseFile}}
          draft: true
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}